import { useState } from 'react';
import { Link } from 'react-router-dom';
import { parseUploadedWorkbook } from '../lib/uploadedFileWorkbook';
import type { UploadColumnMapping } from '../lib/uploadedFileMapping';
import { useUploadedFiles } from '../hooks/useUploadedFiles';
import { ErrorState, Spinner } from '../components/ui';

const roles: { key: keyof UploadColumnMapping; label: string }[] = [
  { key: 'email', label: 'Email' }, { key: 'companyName', label: 'Company name' }, { key: 'firstName', label: 'First name' }, { key: 'lastName', label: 'Last name' }, { key: 'fullName', label: 'Full name' }, { key: 'dealName', label: 'Deal name' }, { key: 'dealStage', label: 'Deal stage' }, { key: 'lastActivityDate', label: 'Last activity date' },
];

export function UploadedFiles() {
  const { list, create, remove } = useUploadedFiles(); const [sheet, setSheet] = useState<Awaited<ReturnType<typeof parseUploadedWorkbook>>['sheets'][number] | null>(null); const [file, setFile] = useState<File | null>(null); const [mapping, setMapping] = useState<UploadColumnMapping>({}); const [error, setError] = useState<string | null>(null);
  async function choose(input: File | null) { if (!input) return; try { const workbook = await parseUploadedWorkbook(input); setFile(input); setSheet(workbook.sheets[0]); setMapping({}); setError(null); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } }
  async function save() { if (!file || !sheet) return; try { await create.mutateAsync({ fileName: file.name, mimeType: file.type, sheetName: sheet.name, headers: sheet.headers, mapping, rows: sheet.rows }); setFile(null); setSheet(null); setMapping({}); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } }
  return <div className="space-y-5"><div><h1 className="text-2xl font-semibold">Uploaded files</h1><p className="text-sm text-slate-500">Saved separately from HubSpot sync. Choose mappings only for the fields you want to match or merge.</p></div><div className="card space-y-3 p-4"><input type="file" accept=".xlsx,.xlsm,.csv" onChange={(e) => void choose(e.target.files?.[0] ?? null)} />{sheet && <><div className="text-sm">Sheet: <b>{sheet.name}</b> · {sheet.rows.length.toLocaleString()} rows</div><div className="grid gap-2 sm:grid-cols-2">{roles.map((role) => <label key={role.key} className="text-sm">{role.label}<select className="input mt-1" value={mapping[role.key] ?? ''} onChange={(e) => setMapping((current) => ({ ...current, [role.key]: e.target.value || null }))}><option value="">Not mapped</option>{sheet.headers.map((header) => <option key={header} value={header}>{header}</option>)}</select></label>)}</div><button className="btn-primary" disabled={create.isPending} onClick={() => void save()}>{create.isPending ? 'Saving…' : 'Save uploaded file'}</button></>}</div>{error && <ErrorState error={error} />}{list.isLoading ? <Spinner label="Loading uploaded files…" /> : <div className="card overflow-x-auto"><table className="min-w-full text-sm"><thead><tr className="border-b text-left"><th className="p-3">File</th><th>Sheet</th><th>Rows</th><th>Status</th><th></th></tr></thead><tbody>{(list.data ?? []).map((item) => { const locked = (item.uploaded_file_merges ?? []).some((merge) => merge.successful_row_count > 0); return <tr key={item.id} className="border-b"><td className="p-3"><Link className="text-brand-600 underline" to={`/uploaded-files/${item.id}`}>{item.file_name}</Link></td><td>{item.sheet_name}</td><td>{item.row_count}</td><td>{locked ? 'Merged — protected' : 'Separate file'}</td><td className="p-3"><button className="btn-secondary text-red-600" disabled={locked || remove.isPending} onClick={() => window.confirm(`Delete ${item.file_name}?`) && void remove.mutate(item.id)}>Delete</button></td></tr>; })}</tbody></table>{(list.data ?? []).length === 0 && <p className="p-6 text-center text-sm text-slate-500">No uploaded files yet.</p>}</div>}</div>;
}
