import {errorResponse,handleOptions,json} from '../_shared/cors.ts';
import {getAdminClient,getUserId} from '../_shared/supabaseAdmin.ts';
import {assertWorkspaceArchivePointer,getArchiveJson,putVerifiedArchive,sha256Hex,verifyArchivePayload,workspaceArchiveManifestKey,workspaceArchiveObjectKey} from '../_shared/r2Archive.ts';
import {archiveTableSpec,assertArchivePayload,LEGACY_ARCHIVE_CHUNK_ROWS,LEGACY_ARCHIVE_EXCLUDED,LEGACY_ARCHIVE_SCHEMA,LEGACY_ARCHIVE_TABLES,sanitizeArchiveRows} from '../_shared/legacyWorkspaceArchive.ts';
import {createArchiveCursor,decodeArchiveCursor,projectArchiveRow} from './archiveBrowse.ts';
import {buildRestoreSet,type RestoreTable} from './archiveRestoreRecord.ts';

type Action='archive'|'restore'|'restore_record'|'dry_run_delete'|'delete'|'status'|'browse'|'record';
type Body={action?:Action;workspace_id?:string;archive_id?:string;confirmation?:string;table?:string;cursor?:string;page_size?:number;search?:string;record_id?:string};
type ArchiveRow={id:string;workspace_id:string;status:string;manifest_key:string|null;manifest_sha256:string|null;table_counts:Record<string,number>;restore_status:string;source_version:number;created_at?:string};
type TableProgress={table_name:string;restore_order:number;status:string;cursor_value:string|null;high_water:string|null;object_count:number;row_count:number;lease_token?:string|null;lease_expires_at?:string|null};
type ObjectRow={id:string;table_name:string;sequence:number;r2_key:string;r2_sha256:string;row_count:number;first_key?:string;last_key?:string;status:string;restore_status:string;restore_row_count:number;deletion_verified_at?:string|null};

const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const DELETION_VERIFY_BATCH=25;

async function assertOwner(admin:ReturnType<typeof getAdminClient>,workspaceId:string,userId:string){
  const{data,error}=await admin.from('workspaces').select('id,kind,created_by').eq('id',workspaceId).eq('kind','legacy').eq('created_by',userId).maybeSingle();
  if(error)throw error;if(!data)throw new Error('Legacy workspace owner required.');const membership=await admin.from('workspace_members').select('role').eq('workspace_id',workspaceId).eq('user_id',userId).eq('role','owner').maybeSingle();if(membership.error)throw membership.error;if(!membership.data)throw new Error('Current legacy workspace owner membership required.');
}

async function loadArchive(admin:ReturnType<typeof getAdminClient>,workspaceId:string,archiveId:string,userId:string){
  await assertOwner(admin,workspaceId,userId);
  const{data,error}=await admin.from('workspace_archives').select('id,workspace_id,status,manifest_key,manifest_sha256,table_counts,restore_status,source_version,created_at').eq('id',archiveId).eq('workspace_id',workspaceId).eq('created_by',userId).maybeSingle();
  if(error)throw error;if(!data)throw new Error('Workspace archive not found.');return data as ArchiveRow;
}

function cursorSecret(){const value=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!value)throw new Error('Archive cursor signing is not configured.');return value;}

async function browseArchive(admin:ReturnType<typeof getAdminClient>,archive:ArchiveRow,userId:string,body:Body){
  if(!['verified','deletion_eligible','deleted'].includes(archive.status))throw new Error('Only a verified archive can be browsed.');
  const table=body.table??'';archiveTableSpec(table);if(!['companies','deals','contacts'].includes(table))throw new Error('Workspace archive table is not browse allow-listed.');
  const pageSize=Math.min(100,Math.max(1,Number(body.page_size??50)));const expected={archiveId:archive.id,workspaceId:archive.workspace_id,ownerId:userId,table};
  const position=body.cursor?await decodeArchiveCursor(cursorSecret(),body.cursor,expected):{...expected,sequence:0,offset:0};
  const metadata=await admin.from('workspace_archive_objects').select('id,table_name,sequence,r2_key,r2_sha256,row_count,status').eq('archive_id',archive.id).eq('workspace_id',archive.workspace_id).eq('table_name',table).gte('sequence',position.sequence).order('sequence').limit(2);
  if(metadata.error)throw metadata.error;const rows:Record<string,unknown>[]=[];let nextSequence=position.sequence;let nextOffset=position.offset;let objectsRead=0;const search=(body.search??'').trim().toLowerCase().slice(0,120);
  for(const object of (metadata.data??[]) as ObjectRow[]){objectsRead++;assertWorkspaceArchivePointer(object.r2_key,userId,archive.workspace_id,archive.id);const payload=await getArchiveJson<unknown>(object.r2_key);await verifyArchivePayload(JSON.stringify(payload),object.r2_sha256);assertArchivePayload(payload,{archiveId:archive.id,workspaceId:archive.workspace_id,ownerId:userId,table,sequence:object.sequence});let offset=object.sequence===position.sequence?position.offset:0;
    for(;offset<payload.rows.length;offset++){const projected=projectArchiveRow(table,payload.rows[offset]);const matches=!search||Object.values(projected).some((value)=>String(value??'').toLowerCase().includes(search));if(matches)rows.push({...projected,_archive_cursor:await createArchiveCursor(cursorSecret(),{...expected,sequence:object.sequence,offset})});if(rows.length>=pageSize){nextSequence=object.sequence;nextOffset=offset+1;break;}}
    if(rows.length>=pageSize)break;nextSequence=object.sequence+1;nextOffset=0;
  }
  const tableState=await admin.from('workspace_archive_tables').select('row_count,object_count').eq('archive_id',archive.id).eq('workspace_id',archive.workspace_id).eq('table_name',table).maybeSingle();if(tableState.error)throw tableState.error;
  const complete=(metadata.data??[]).length<2&&rows.length<pageSize;const cursor=complete?null:await createArchiveCursor(cursorSecret(),{...expected,sequence:nextSequence,offset:nextOffset});
  return{ok:true,archive_id:archive.id,table,rows,cursor,progress:{objects_read:objectsRead,total_objects:Number(tableState.data?.object_count??0),total_rows:Number(tableState.data?.row_count??0)},read_only:true,archived_at:archive.created_at??null};
}

async function archivedRecord(admin:ReturnType<typeof getAdminClient>,archive:ArchiveRow,userId:string,body:Body){
  if(!body.cursor||!body.record_id)throw new Error('record cursor and record_id are required.');const table=body.table??'';const expected={archiveId:archive.id,workspaceId:archive.workspace_id,ownerId:userId,table};const position=await decodeArchiveCursor(cursorSecret(),body.cursor,expected);
  const object=await admin.from('workspace_archive_objects').select('id,table_name,sequence,r2_key,r2_sha256,row_count,status').eq('archive_id',archive.id).eq('workspace_id',archive.workspace_id).eq('table_name',table).eq('sequence',position.sequence).maybeSingle();if(object.error)throw object.error;if(!object.data)throw new Error('Archived record not found.');const metadata=object.data as ObjectRow;assertWorkspaceArchivePointer(metadata.r2_key,userId,archive.workspace_id,archive.id);const payload=await getArchiveJson<unknown>(metadata.r2_key);await verifyArchivePayload(JSON.stringify(payload),metadata.r2_sha256);assertArchivePayload(payload,{archiveId:archive.id,workspaceId:archive.workspace_id,ownerId:userId,table,sequence:metadata.sequence});const row=payload.rows[position.offset];if(!row||String(row.id)!==body.record_id)throw new Error('Archived record cursor does not match the requested record.');return{ok:true,archive_id:archive.id,table,row:projectArchiveRow(table,row),read_only:true};
}

async function verifiedArchivedRowById(admin:ReturnType<typeof getAdminClient>,archive:ArchiveRow,userId:string,table:RestoreTable,id:string){
  const object=await admin.from('workspace_archive_objects').select('id,table_name,sequence,r2_key,r2_sha256,row_count,status').eq('archive_id',archive.id).eq('workspace_id',archive.workspace_id).eq('table_name',table).lte('first_key',id).gte('last_key',id).order('sequence').limit(1).maybeSingle();if(object.error)throw object.error;if(!object.data)return null;const metadata=object.data as ObjectRow;assertWorkspaceArchivePointer(metadata.r2_key,userId,archive.workspace_id,archive.id);const payload=await getArchiveJson<unknown>(metadata.r2_key);await verifyArchivePayload(JSON.stringify(payload),metadata.r2_sha256);assertArchivePayload(payload,{archiveId:archive.id,workspaceId:archive.workspace_id,ownerId:userId,table,sequence:metadata.sequence});return payload.rows.find((row)=>String(row.id)===id)??null;
}

async function restoreArchivedRecord(admin:ReturnType<typeof getAdminClient>,archive:ArchiveRow,userId:string,body:Body){
  if(!['verified','deletion_eligible','deleted'].includes(archive.status))throw new Error('Only a verified archive can restore records.');if(!body.cursor||!body.record_id||!body.table)throw new Error('table, record cursor, and record_id are required.');if(!['companies','deals','contacts'].includes(body.table))throw new Error('Archived record table is not restore allow-listed.');
  const expected={archiveId:archive.id,workspaceId:archive.workspace_id,ownerId:userId,table:body.table};const position=await decodeArchiveCursor(cursorSecret(),body.cursor,expected);const object=await admin.from('workspace_archive_objects').select('id,table_name,sequence,r2_key,r2_sha256,row_count,status').eq('archive_id',archive.id).eq('workspace_id',archive.workspace_id).eq('table_name',body.table).eq('sequence',position.sequence).maybeSingle();if(object.error)throw object.error;if(!object.data)throw new Error('Archived record not found.');const metadata=object.data as ObjectRow;assertWorkspaceArchivePointer(metadata.r2_key,userId,archive.workspace_id,archive.id);const payload=await getArchiveJson<unknown>(metadata.r2_key);await verifyArchivePayload(JSON.stringify(payload),metadata.r2_sha256);assertArchivePayload(payload,{archiveId:archive.id,workspaceId:archive.workspace_id,ownerId:userId,table:body.table,sequence:metadata.sequence});const target=payload.rows[position.offset];if(!target||String(target.id)!==body.record_id)throw new Error('Archived record cursor does not match the requested record.');
  const records=await buildRestoreSet(body.table as RestoreTable,target,userId,async(_table,id)=>verifiedArchivedRowById(admin,archive,userId,'companies',id));const restored=await admin.rpc('restore_archived_legacy_records',{p_owner_id:userId,p_records:records});if(restored.error)throw restored.error;return{ok:true,archive_id:archive.id,table:body.table,record_id:body.record_id,...restored.data};
}

async function beginArchive(admin:ReturnType<typeof getAdminClient>,workspaceId:string,userId:string){
  await assertOwner(admin,workspaceId,userId);
  const existing=await admin.from('workspace_archives').select('id,workspace_id,status,manifest_key,manifest_sha256,table_counts,restore_status,source_version').eq('workspace_id',workspaceId).eq('status','building').order('created_at',{ascending:false}).limit(1).maybeSingle();
  if(existing.error)throw existing.error;let archive=existing.data as ArchiveRow|null;
  if(!archive){const initializedVersion=await admin.from('legacy_data_versions').upsert({owner_id:userId,version:0},{onConflict:'owner_id',ignoreDuplicates:true});if(initializedVersion.error)throw initializedVersion.error;const version=await admin.from('legacy_data_versions').select('version').eq('owner_id',userId).single();if(version.error)throw version.error;const created=await admin.from('workspace_archives').insert({workspace_id:workspaceId,archive_version:1,schema_version:LEGACY_ARCHIVE_SCHEMA,status:'building',created_by:userId,source_version:Number(version.data.version)}).select('id,workspace_id,status,manifest_key,manifest_sha256,table_counts,restore_status,source_version').single();if(created.error?.code==='23505'){const winner=await admin.from('workspace_archives').select('id,workspace_id,status,manifest_key,manifest_sha256,table_counts,restore_status,source_version').eq('workspace_id',workspaceId).eq('status','building').single();if(winner.error)throw winner.error;archive=winner.data as ArchiveRow;}else{if(created.error)throw created.error;archive=created.data as ArchiveRow;}}
  const states=LEGACY_ARCHIVE_TABLES.map((spec)=>({archive_id:archive!.id,workspace_id:workspaceId,table_name:spec.table,restore_order:spec.restoreOrder}));
  const initialized=await admin.from('workspace_archive_tables').upsert(states,{onConflict:'archive_id,table_name',ignoreDuplicates:true});if(initialized.error)throw initialized.error;
  return archive;
}

async function allObjects(admin:ReturnType<typeof getAdminClient>,archiveId:string){const rows:ObjectRow[]=[];for(let from=0;;from+=1000){const{data,error}=await admin.from('workspace_archive_objects').select('id,table_name,sequence,r2_key,r2_sha256,row_count,first_key,last_key,status,restore_status,restore_row_count,deletion_verified_at').eq('archive_id',archiveId).order('table_name').order('sequence').range(from,from+999);if(error)throw error;rows.push(...(data??[]) as ObjectRow[]);if((data??[]).length<1000)break;}return rows;}

async function finalizeArchive(admin:ReturnType<typeof getAdminClient>,archive:ArchiveRow,userId:string){
  const version=await admin.from('legacy_data_versions').select('version').eq('owner_id',userId).maybeSingle();if(version.error)throw version.error;if(Number(version.data?.version??0)!==Number(archive.source_version)){await admin.from('workspace_archives').update({status:'failed',last_error:'Legacy data changed while the archive was being built.'}).eq('id',archive.id);throw new Error('Archive verification refused because legacy data changed during capture. Start a new archive.');}
  const objects=await allObjects(admin,archive.id);if(objects.some((item)=>item.status!=='verified'))throw new Error('Archive contains an unverified object.');for(const object of objects)assertWorkspaceArchivePointer(object.r2_key,userId,archive.workspace_id,archive.id);
  const{data:states,error}=await admin.from('workspace_archive_tables').select('table_name,row_count,status').eq('archive_id',archive.id).order('restore_order');if(error)throw error;
  if((states??[]).some((item)=>item.status!=='verified'))return null;
  const tableCounts:Record<string,number>=Object.fromEntries((states??[]).map((item)=>[item.table_name,Number(item.row_count)]));
  if(objects.reduce((sum,item)=>sum+item.row_count,0)!==Object.values(tableCounts).reduce((sum,count)=>sum+count,0))throw new Error('Archive row counts do not reconcile.');
  const payload={format:LEGACY_ARCHIVE_SCHEMA,archive_id:archive.id,workspace_id:archive.workspace_id,owner_id:userId,created_at:new Date().toISOString(),excluded:LEGACY_ARCHIVE_EXCLUDED,table_counts:tableCounts,objects:objects.map(({table_name,sequence,r2_key,r2_sha256,row_count})=>({table_name,sequence,r2_key,r2_sha256,row_count}))};
  const manifestChecksum=await sha256Hex(JSON.stringify(payload));const stored=await putVerifiedArchive(workspaceArchiveManifestKey(userId,archive.workspace_id,archive.id,manifestChecksum),payload);
  const updated=await admin.rpc('finalize_legacy_workspace_archive',{p_archive_id:archive.id,p_owner_id:userId,p_manifest_key:stored.key,p_manifest_sha256:stored.checksum,p_table_counts:tableCounts});if(updated.error){await admin.from('workspace_archives').update({status:'failed',last_error:'Legacy data changed while the archive was being finalized.'}).eq('id',archive.id).eq('status','building');throw updated.error;}
  return{...stored,table_counts:tableCounts};
}

async function archiveStep(admin:ReturnType<typeof getAdminClient>,workspaceId:string,userId:string){
  const archive=await beginArchive(admin,workspaceId,userId);
  const progress=await admin.from('workspace_archive_tables').select('table_name,restore_order,status,cursor_value,high_water,object_count,row_count,lease_token,lease_expires_at').eq('archive_id',archive.id).neq('status','verified').order('restore_order').limit(1).maybeSingle();if(progress.error)throw progress.error;
  if(!progress.data){const manifest=await finalizeArchive(admin,archive,userId);return{ok:true,archive_id:archive.id,status:manifest?'verified':'building',manifest};}
  const state=progress.data as TableProgress;const spec=archiveTableSpec(state.table_name);const leaseToken=crypto.randomUUID();const now=new Date().toISOString();const leaseUntil=new Date(Date.now()+5*60_000).toISOString();
  const claim=await admin.from('workspace_archive_tables').update({lease_token:leaseToken,lease_expires_at:leaseUntil,status:'archiving'}).eq('archive_id',archive.id).eq('table_name',spec.table).or(`lease_token.is.null,lease_expires_at.lt.${now}`).select('table_name').maybeSingle();if(claim.error)throw claim.error;if(!claim.data)return{ok:true,archive_id:archive.id,status:'busy',table:spec.table,rows:0,complete:false};
  try{
    let highWater=state.high_water;if(!highWater){const top=await admin.from(spec.table).select(spec.cursorColumn).eq(spec.ownerColumn,userId).order(spec.cursorColumn,{ascending:false}).limit(1).maybeSingle();if(top.error)throw top.error;highWater=top.data?String((top.data as unknown as Record<string,unknown>)[spec.cursorColumn]):null;if(highWater){const boundary=await admin.from('workspace_archive_tables').update({high_water:highWater}).eq('archive_id',archive.id).eq('table_name',spec.table).eq('lease_token',leaseToken).select('table_name').maybeSingle();if(boundary.error)throw boundary.error;if(!boundary.data)throw new Error('Archive step lease was lost.');}}
    if(!highWater){const done=await admin.from('workspace_archive_tables').update({status:'verified',high_water:null,lease_token:null,lease_expires_at:null,completed_at:new Date().toISOString()}).eq('archive_id',archive.id).eq('table_name',spec.table).eq('lease_token',leaseToken).select('table_name').maybeSingle();if(done.error)throw done.error;if(!done.data)throw new Error('Archive step lease was lost.');return{ok:true,archive_id:archive.id,status:'building',table:spec.table,rows:0,complete:true};}
    const sequence=state.object_count;const existing=await admin.from('workspace_archive_objects').select('id,table_name,sequence,r2_key,r2_sha256,row_count,first_key,last_key,status,restore_status,restore_row_count').eq('archive_id',archive.id).eq('table_name',spec.table).eq('sequence',sequence).maybeSingle();if(existing.error)throw existing.error;
    let object=existing.data as ObjectRow|null;
    if(object){assertWorkspaceArchivePointer(object.r2_key,userId,workspaceId,archive.id);const prior=await getArchiveJson<unknown>(object.r2_key);await verifyArchivePayload(JSON.stringify(prior),object.r2_sha256);assertArchivePayload(prior,{archiveId:archive.id,workspaceId,ownerId:userId,table:spec.table,sequence});}
    else{let query=admin.from(spec.table).select('*').eq(spec.ownerColumn,userId).lte(spec.cursorColumn,highWater).order(spec.cursorColumn,{ascending:true}).limit(LEGACY_ARCHIVE_CHUNK_ROWS);if(state.cursor_value)query=query.gt(spec.cursorColumn,state.cursor_value);const result=await query;if(result.error)throw result.error;const rows=sanitizeArchiveRows(spec,(result.data??[]) as Record<string,unknown>[]);if(rows.length===0){const done=await admin.from('workspace_archive_tables').update({status:'verified',high_water:highWater,lease_token:null,lease_expires_at:null,completed_at:new Date().toISOString()}).eq('archive_id',archive.id).eq('table_name',spec.table).eq('lease_token',leaseToken).select('table_name').maybeSingle();if(done.error)throw done.error;if(!done.data)throw new Error('Archive step lease was lost.');return{ok:true,archive_id:archive.id,status:'building',table:spec.table,rows:0,complete:true};}const payload={format:LEGACY_ARCHIVE_SCHEMA,archive_id:archive.id,workspace_id:workspaceId,owner_id:userId,table:spec.table,sequence,rows};const checksum=await sha256Hex(JSON.stringify(payload));const stored=await putVerifiedArchive(workspaceArchiveObjectKey(userId,workspaceId,archive.id,spec.table,sequence,checksum),payload);const firstKey=String(rows[0][spec.cursorColumn]);const lastKey=String(rows.at(-1)![spec.cursorColumn]);const inserted=await admin.from('workspace_archive_objects').insert({archive_id:archive.id,workspace_id:workspaceId,table_name:spec.table,sequence,r2_key:stored.key,r2_sha256:stored.checksum,row_count:rows.length,first_key:firstKey,last_key:lastKey,status:'verified',verified_at:new Date().toISOString()}).select('id,table_name,sequence,r2_key,r2_sha256,row_count,first_key,last_key,status,restore_status,restore_row_count').maybeSingle();if(inserted.error&&inserted.error.code!=='23505')throw inserted.error;if(inserted.error){const winner=await admin.from('workspace_archive_objects').select('id,table_name,sequence,r2_key,r2_sha256,row_count,first_key,last_key,status,restore_status,restore_row_count').eq('archive_id',archive.id).eq('table_name',spec.table).eq('sequence',sequence).single();if(winner.error)throw winner.error;object=winner.data as ObjectRow;}else object=inserted.data as ObjectRow;}
    const complete=object!.last_key===highWater||object!.row_count<LEGACY_ARCHIVE_CHUNK_ROWS;const updated=await admin.from('workspace_archive_tables').update({cursor_value:object!.last_key,high_water:highWater,object_count:sequence+1,row_count:state.row_count+object!.row_count,status:complete?'verified':'archiving',lease_token:null,lease_expires_at:null,completed_at:complete?new Date().toISOString():null}).eq('archive_id',archive.id).eq('table_name',spec.table).eq('lease_token',leaseToken).eq('object_count',sequence).select('table_name').maybeSingle();if(updated.error)throw updated.error;if(!updated.data)throw new Error('Archive step lease was lost.');return{ok:true,archive_id:archive.id,status:'building',table:spec.table,rows:object!.row_count,complete};
  }catch(error){await admin.from('workspace_archive_tables').update({lease_token:null,lease_expires_at:null,status:'failed'}).eq('archive_id',archive.id).eq('table_name',spec.table).eq('lease_token',leaseToken);throw error;}
}

async function restoreStep(admin:ReturnType<typeof getAdminClient>,archive:ArchiveRow,userId:string){
  if(!['verified','deletion_eligible','deleted'].includes(archive.status))throw new Error('Only a verified archive can be restored.');
  for(const spec of LEGACY_ARCHIVE_TABLES){const next=await admin.from('workspace_archive_objects').select('id,table_name,sequence,r2_key,r2_sha256,row_count,status,restore_status,restore_row_count').eq('archive_id',archive.id).eq('table_name',spec.table).neq('restore_status','restored').order('sequence').limit(1).maybeSingle();if(next.error)throw next.error;if(!next.data)continue;const object=next.data as ObjectRow;
    try{assertWorkspaceArchivePointer(object.r2_key,userId,archive.workspace_id,archive.id);const payload=await getArchiveJson<unknown>(object.r2_key);await verifyArchivePayload(JSON.stringify(payload),object.r2_sha256);assertArchivePayload(payload,{archiveId:archive.id,workspaceId:archive.workspace_id,ownerId:userId,table:spec.table,sequence:object.sequence});if(spec.onConflict==='id'){const ids=payload.rows.map((row)=>String(row.id));const conflicts=await admin.from(spec.table).select(`id,${spec.ownerColumn}`).in('id',ids);if(conflicts.error)throw conflicts.error;if((conflicts.data??[]).some((row)=>(row as Record<string,unknown>)[spec.ownerColumn]!==userId))throw new Error('Restore refused: a primary key belongs to another owner.');}const restored=await admin.from(spec.table).upsert(payload.rows,{onConflict:spec.onConflict});if(restored.error)throw restored.error;const saved=await admin.from('workspace_archive_objects').update({restore_status:'restored',restore_row_count:payload.rows.length,restored_at:new Date().toISOString(),last_error:null}).eq('id',object.id);if(saved.error)throw saved.error;await admin.from('workspace_archives').update({restore_status:'restoring',last_error:null}).eq('id',archive.id);return{ok:true,archive_id:archive.id,status:'restoring',table:spec.table,rows:payload.rows.length};}catch(error){await admin.from('workspace_archive_objects').update({restore_status:'failed',last_error:error instanceof Error?error.message:String(error)}).eq('id',object.id);await admin.from('workspace_archives').update({restore_status:'failed',last_error:error instanceof Error?error.message:String(error)}).eq('id',archive.id);throw error;}}
  const objects=await allObjects(admin,archive.id);if(objects.some((item)=>item.restore_status!=='restored')||objects.reduce((sum,item)=>sum+item.restore_row_count,0)!==objects.reduce((sum,item)=>sum+item.row_count,0))throw new Error('Restored archive row counts do not reconcile.');
  const done=await admin.from('workspace_archives').update({restore_status:'verified',restored_at:new Date().toISOString(),last_error:null}).eq('id',archive.id);if(done.error)throw done.error;return{ok:true,archive_id:archive.id,status:'restored',rows:objects.reduce((sum,item)=>sum+item.row_count,0)};
}

async function deletionDryRun(admin:ReturnType<typeof getAdminClient>,archive:ArchiveRow,userId:string){
  if(archive.status!=='verified'&&archive.status!=='deletion_eligible')throw new Error('Deletion refused: archive is not verified.');if(!archive.manifest_key||!archive.manifest_sha256)throw new Error('Deletion refused: verified manifest pointer is missing.');assertWorkspaceArchivePointer(archive.manifest_key,userId,archive.workspace_id,archive.id);
  const currentVersion=await admin.from('legacy_data_versions').select('version').eq('owner_id',userId).single();if(currentVersion.error)throw currentVersion.error;if(Number(currentVersion.data.version)!==Number(archive.source_version))throw new Error('Deletion refused: legacy data changed after this archive was captured.');
  const manifest=await getArchiveJson<any>(archive.manifest_key);await verifyArchivePayload(JSON.stringify(manifest),archive.manifest_sha256);if(manifest.format!==LEGACY_ARCHIVE_SCHEMA||manifest.archive_id!==archive.id||manifest.workspace_id!==archive.workspace_id||manifest.owner_id!==userId)throw new Error('Deletion refused: manifest identity mismatch.');
  const pending=await admin.from('workspace_archive_objects').select('id,table_name,sequence,r2_key,r2_sha256,row_count,status').eq('archive_id',archive.id).is('deletion_verified_at',null).order('table_name').order('sequence').limit(DELETION_VERIFY_BATCH);if(pending.error)throw pending.error;
  if((pending.data??[]).length){for(const item of pending.data as ObjectRow[]){assertWorkspaceArchivePointer(item.r2_key,userId,archive.workspace_id,archive.id);const payload=await getArchiveJson<unknown>(item.r2_key);await verifyArchivePayload(JSON.stringify(payload),item.r2_sha256);assertArchivePayload(payload,{archiveId:archive.id,workspaceId:archive.workspace_id,ownerId:userId,table:item.table_name,sequence:item.sequence});if(payload.rows.length!==item.row_count)throw new Error('Deletion refused: archive object row count mismatch.');const checked=await admin.from('workspace_archive_objects').update({deletion_verified_at:new Date().toISOString()}).eq('id',item.id).eq('r2_sha256',item.r2_sha256).is('deletion_verified_at',null);if(checked.error)throw checked.error;}return{ok:true,archive_id:archive.id,status:'verifying',eligible:false,deleted:false,verification_pending:true,verified_objects:(pending.data??[]).length,message:`Verified ${(pending.data??[]).length} archive objects. Continue verification until the archive is deletion eligible.`};}
  const objects=await allObjects(admin,archive.id);const count=objects.reduce((sum,item)=>sum+item.row_count,0);const expected=Object.values(archive.table_counts??{}).reduce((sum,value)=>sum+Number(value),0);const manifestObjects=Array.isArray(manifest.objects)?manifest.objects:[];const objectMap=new Map(objects.map((item)=>[`${item.table_name}:${item.sequence}`,item]));const manifestMatches=manifestObjects.length===objects.length&&manifestObjects.every((item:any)=>{const stored=objectMap.get(`${item.table_name}:${item.sequence}`);return stored?.r2_key===item.r2_key&&stored?.r2_sha256===item.r2_sha256&&stored?.row_count===item.row_count;});const normalizedCounts=(value:Record<string,unknown>)=>JSON.stringify(Object.entries(value??{}).sort(([left],[right])=>left.localeCompare(right)));if(objects.some((item)=>item.status!=='verified')||count!==expected||!manifestMatches||normalizedCounts(manifest.table_counts)!==normalizedCounts(archive.table_counts))throw new Error('Deletion refused: archive objects or row counts are incomplete.');
  const marked=await admin.rpc('mark_legacy_workspace_archive_deletion_eligible',{p_archive_id:archive.id,p_owner_id:userId});if(marked.error)throw marked.error;return{ok:true,archive_id:archive.id,eligible:true,deleted:false,row_count:count,message:'Dry run only. No legacy rows were deleted.'};
}

async function deleteStep(admin:ReturnType<typeof getAdminClient>,archive:ArchiveRow,userId:string,confirmation:string|undefined){
  if(!['deletion_eligible','deleting'].includes(archive.status))throw new Error('Deletion refused: archive is not deletion eligible.');
  const expected=Object.values(archive.table_counts??{}).reduce((sum,value)=>sum+Number(value),0);
  if(confirmation!==`DELETE ${expected}`)throw new Error(`Type DELETE ${expected} to confirm deletion.`);
  if(!archive.manifest_key||!archive.manifest_sha256)throw new Error('Deletion refused: verified manifest pointer is missing.');assertWorkspaceArchivePointer(archive.manifest_key,userId,archive.workspace_id,archive.id);
  const manifest=await getArchiveJson<any>(archive.manifest_key);await verifyArchivePayload(JSON.stringify(manifest),archive.manifest_sha256);if(manifest.format!==LEGACY_ARCHIVE_SCHEMA||manifest.archive_id!==archive.id||manifest.workspace_id!==archive.workspace_id||manifest.owner_id!==userId)throw new Error('Deletion refused: manifest identity mismatch.');
  const result=await admin.rpc('delete_legacy_workspace_archive_batch',{p_archive_id:archive.id,p_owner_id:userId,p_batch_size:5000});if(result.error)throw result.error;
  const value=Array.isArray(result.data)?result.data[0]:result.data;const row=(value??{}) as Record<string,unknown>;
  return{ok:true,archive_id:archive.id,status:String(row.status??'deleting'),table:row.table_name?String(row.table_name):undefined,rows:Number(row.deleted_rows??0),total_deleted_rows:Number(row.total_deleted_rows??0),retained_rows:Number(row.retained_rows??0),total_retained_rows:Number(row.total_retained_rows??0),complete:Boolean(row.complete),deleted:row.status==='deleted'};
}

Deno.serve(async(req)=>{const preflight=handleOptions(req);if(preflight)return preflight;try{const userId=await getUserId(req);const body=await req.json().catch(()=>({})) as Body;const action=body.action??'status';if(!body.workspace_id||!uuid.test(body.workspace_id))return errorResponse('valid workspace_id is required',400);const admin=getAdminClient();if(action==='archive')return json(await archiveStep(admin,body.workspace_id,userId));if(!body.archive_id||!uuid.test(body.archive_id))return errorResponse('valid archive_id is required',400);const archive=await loadArchive(admin,body.workspace_id,body.archive_id,userId);if(action==='browse')return json(await browseArchive(admin,archive,userId,body));if(action==='record')return json(await archivedRecord(admin,archive,userId,body));if(action==='restore_record')return json(await restoreArchivedRecord(admin,archive,userId,body));if(action==='restore')return json(await restoreStep(admin,archive,userId));if(action==='dry_run_delete')return json(await deletionDryRun(admin,archive,userId));if(action==='delete')return json(await deleteStep(admin,archive,userId,body.confirmation));if(action==='status')return json({ok:true,archive});return errorResponse('unsupported archive action',400);}catch(error){return errorResponse(error instanceof Error?error.message:'Workspace archive failed',500);}});
