-- Service-only history for the capacity-triggered R2 archive worker. The
-- dashboard reads this through the authenticated storage-status Edge Function.
create table if not exists public.storage_archive_runs (
  id bigint generated by default as identity primary key,
  status text not null check (status in ('succeeded', 'degraded', 'failed')),
  pressure text not null check (pressure in ('warning', 'critical')),
  database_bytes bigint not null check (database_bytes >= 0),
  limit_bytes bigint not null check (limit_bytes > 0),
  owners_processed integer not null default 0 check (owners_processed >= 0),
  deals_archived integer not null default 0 check (deals_archived >= 0),
  generic_attachments_archived integer not null default 0 check (generic_attachments_archived >= 0),
  warnings jsonb not null default '[]'::jsonb,
  error text,
  finished_at timestamptz not null default now()
);

create index if not exists storage_archive_runs_finished_at_idx
  on public.storage_archive_runs (finished_at desc);

alter table public.storage_archive_runs enable row level security;
revoke all on table public.storage_archive_runs from anon, authenticated;
grant all on table public.storage_archive_runs to service_role;
grant usage, select on sequence public.storage_archive_runs_id_seq to service_role;

comment on table public.storage_archive_runs is
  'Service-role-only history for automatic R2 storage-pressure archive runs.';

create table if not exists public.storage_archive_state (
  id boolean primary key default true check (id),
  lease_token uuid,
  lease_expires_at timestamptz
);

alter table public.storage_archive_state enable row level security;
revoke all on table public.storage_archive_state from anon, authenticated;
grant all on table public.storage_archive_state to service_role;

create or replace function public.claim_storage_archive_lease(p_lease_seconds integer default 600)
returns uuid
language plpgsql
security invoker
set search_path = public
as $$
declare
  claimed_token uuid := gen_random_uuid();
begin
  insert into public.storage_archive_state (id, lease_token, lease_expires_at)
  values (true, claimed_token, now() + make_interval(secs => greatest(30, least(p_lease_seconds, 600))))
  on conflict (id) do update
  set lease_token = excluded.lease_token,
      lease_expires_at = excluded.lease_expires_at
  where public.storage_archive_state.lease_expires_at is null
     or public.storage_archive_state.lease_expires_at < now()
  returning lease_token into claimed_token;

  if not found then return null; end if;
  return claimed_token;
end;
$$;

create or replace function public.release_storage_archive_lease(p_token uuid)
returns boolean
language plpgsql
security invoker
set search_path = public
as $$
begin
  update public.storage_archive_state
  set lease_token = null, lease_expires_at = null
  where id and lease_token = p_token;
  return found;
end;
$$;

revoke all on function public.claim_storage_archive_lease(integer) from public, anon, authenticated;
revoke all on function public.release_storage_archive_lease(uuid) from public, anon, authenticated;
grant execute on function public.claim_storage_archive_lease(integer) to service_role;
grant execute on function public.release_storage_archive_lease(uuid) to service_role;

create or replace function public.trim_storage_archive_runs()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  perform public.prune_storage_archive_runs(500);
  return new;
end;
$$;

revoke all on function public.trim_storage_archive_runs() from public, anon, authenticated;
grant execute on function public.trim_storage_archive_runs() to service_role;

drop trigger if exists trim_storage_archive_runs_after_insert on public.storage_archive_runs;
create trigger trim_storage_archive_runs_after_insert
after insert on public.storage_archive_runs
for each statement execute function public.trim_storage_archive_runs();

create or replace function public.storage_archive_owner_candidates()
returns table (owner_id uuid)
language sql
stable
security invoker
set search_path = public
as $$
  select candidate.owner_id
  from (
    select deal.owner_id
    from public.deals deal
    where deal.r2_archive_key is null
      and deal.hubspot_properties is not null
      and deal.hubspot_properties <> '{}'::jsonb
    union
    select attachment.owner_id
    from public.attachments attachment
    join public.deals deal
      on deal.id = attachment.deal_id
     and deal.owner_id = attachment.owner_id
    where attachment.source_type = 'generic'
      and deal.company_id is not null
  ) candidate
  order by candidate.owner_id
  limit 50;
$$;

revoke all on function public.storage_archive_owner_candidates() from public, anon, authenticated;
grant execute on function public.storage_archive_owner_candidates() to service_role;

create or replace function public.prune_storage_archive_runs(p_keep integer default 500)
returns integer
language plpgsql
security invoker
set search_path = public
as $$
declare
  removed integer;
begin
  delete from public.storage_archive_runs run
  where run.id not in (
    select recent.id
    from public.storage_archive_runs recent
    order by recent.finished_at desc, recent.id desc
    limit greatest(10, least(p_keep, 5000))
  );
  get diagnostics removed = row_count;
  return removed;
end;
$$;

revoke all on function public.prune_storage_archive_runs(integer) from public, anon, authenticated;
grant execute on function public.prune_storage_archive_runs(integer) to service_role;

-- Poll every five minutes. The Edge Function itself stays idle below 70%, runs
-- every 15 minutes at warning pressure, and runs on every tick at 85% or above.
-- Reuse the existing private cron secret and derive this sibling Function URL
-- from the already-configured queue worker URL, so no credential enters git.
do $$
declare
  worker_url text;
  cron_secret text;
begin
  create extension if not exists pg_net with schema extensions;
  create extension if not exists pg_cron;

  select
    regexp_replace(worker.decrypted_secret, '/process-email-queue/?$', '/storage-maintenance'),
    secret.decrypted_secret
  into worker_url, cron_secret
  from vault.decrypted_secrets worker
  cross join vault.decrypted_secrets secret
  where worker.name = 'queue_worker_url'
    and secret.name = 'queue_cron_secret'
  limit 1;

  if worker_url is null or cron_secret is null then
    raise notice 'Storage archive cron not installed: queue_worker_url or queue_cron_secret is absent from Vault.';
    return;
  end if;
  if worker_url !~ '/storage-maintenance$' or length(cron_secret) < 16 then
    raise notice 'Storage archive cron not installed: Vault configuration is invalid.';
    return;
  end if;

  perform cron.unschedule(jobid)
  from cron.job
  where jobname = 'storage-pressure-r2-archive';

  perform cron.schedule('storage-pressure-r2-archive', '*/5 * * * *', $job$
    with config as (
      select
        regexp_replace(worker.decrypted_secret, '/process-email-queue/?$', '/storage-maintenance') as worker_url,
        secret.decrypted_secret as cron_secret
      from vault.decrypted_secrets worker
      cross join vault.decrypted_secrets secret
      where worker.name = 'queue_worker_url'
        and secret.name = 'queue_cron_secret'
      limit 1
    )
    select net.http_post(
      url := config.worker_url,
      headers := jsonb_build_object(
        'Content-Type', 'application/json',
        'X-Storage-Cron-Secret', config.cron_secret
      ),
      body := '{}'::jsonb
    )
    from config
    where config.worker_url is not null and config.cron_secret is not null;
  $job$);
end $$;
